Swaad/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Swaad/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Swaad/Controllers/FoodItemController.cs
using Microsoft.AspNetCore.Mvc;
using Swaad.Models;
using Swaad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class FoodItemController : Controller
    {
        private readonly IFoodItemRepo _foodItemRepo;
        private readonly ICategoryRepo _categoryRepo;

        //DI

        public FoodItemController(IFoodItemRepo foodItemRepo, ICategoryRepo categoryRepo)
        {
            _foodItemRepo = foodItemRepo;
            _categoryRepo = categoryRepo;
        }

        public IActionResult Index(string FoodSearch)
        {
            ViewData["GetFoodItems"] = FoodSearch;
            var query = _foodItemRepo.AllFoodItems;
            if(!String.IsNullOrEmpty(FoodSearch))
            {
                query = query.Where(x => x.FoodName.Contains(FoodSearch) || x.FoodDescription.Contains(FoodSearch));
            }
            var foodListViewModel = new FoodListViewModel
            {
                FoodItems = query.ToList(),
                CurrentCategory = ""
            };
            return View(foodListViewModel);
        }
        public IActionResult CategoryFilter(string category)
        {
            IEnumerable<FoodItem> fooditems;
            string currentcategory;

            if (string.IsNullOrEmpty(category))
            {
                fooditems = _foodItemRepo.AllFoodItems.OrderBy(f => f.FoodId);
                currentcategory = "all food dishes";
            }
            else
            {
                fooditems = _foodItemRepo.AllFoodItems.Where(f => f.Category.CategoryName == category).OrderBy(f => f.FoodId);
                currentcategory = _categoryRepo.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            return View(new FoodListViewModel { FoodItems = fooditems, CurrentCategory = currentcategory });
        }

        public IActionResult Details(int id)
        {
            var fooditem = _foodItemRepo.GetFoodItemById(id);
            if (fooditem == null)
            {
                return NotFound();
            }
            return View(fooditem);
        }
    }
}

Swaad/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Swaad.Models;
using Swaad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IFoodItemRepo _foodItemRepo;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IFoodItemRepo foodItemRepo, ShoppingCart shoppingCart)
        {
            _foodItemRepo = foodItemRepo;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
               
            };

            return View(shoppingCartViewModel);

        }

        public RedirectToActionResult AddToShoppingCart(int fooditemid)
        {
            var selectedFoodItem = _foodItemRepo.AllFoodItems.FirstOrDefault(p => p.FoodId == fooditemid);
            if (selectedFoodItem != null)
            {
                _shoppingCart.AddToCart(selectedFoodItem, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int fooditemid)
        {
            var selectedFoodItem = _foodItemRepo.AllFoodItems.FirstOrDefault(p => p.FoodId == fooditemid);
            if (selectedFoodItem != null)
            {
                _shoppingCart.RemoveFromCart(selectedFoodItem);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearShoppingCart()
        {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

Swaad/Views/Shared/_FoodItemCard.cshtml
@model FoodItem

@*<div class="col-sm-3">
    <div class="card-deck">
        <div class="card shadow">
            <img class="card-img-top img-thumbnail" src="@Model.ImageUrl" />
            <div class="card-body">
                <h3 class="pull-right">@Model.Price</h3>
                <a asp-controller="Fooditem" asp-action="Details" asp-route-id="@Model.FoodId">
                    <h3 class="card-title">
                        @Model.FoodName
                    </h3>
                </a>
                <p class="card-text">
                    &ldquo; @Model.FoodDescription &rdquo;
                </p>
                <a class="lnk btn btn-success btn-block mt-2"
                   asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-fooditemid="@Model.FoodId">
                    Add To Cart
                </a>
            </div>
        </div>
    </div>
</div>*@
@*<div class="card-deck">*@
    <div class="col mb-4">
        <div class="card h-100">
            <!-- Sale badge-->
            @if (Model.HasDiscount == true)
            {
                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">50% Discount</div>
            }
            <!-- Product image-->
            <img class="card-img-top" src="@Model.ImageUrl" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">@Model.FoodName</h5>
                    <!-- Product price-->
                    @if (Model.HasDiscount == true)
                    {
                        <span class="text-muted text-decoration-line-through">₹ @(2 * @Model.Price)</span>
                    }
                    ₹ @Model.Price
                </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer">
                <div class="btn-wrapper text-center d-flex justify-content-between">
                    <a class="btn btn-dark  btn-sm text-white d-flex align-items-center" style="width:auto" asp-controller="Fooditem" asp-action="Details" asp-route-id="@Model.FoodId">View</a> &nbsp;
                    <a class="btn btn-dark text-white" asp-controller="ShoppingCart" style="width:auto" asp-action="AddToShoppingCart" asp-route-fooditemid="@Model.FoodId">Add to cart</a>
                </div>
            </div>
        </div>
    </div>
@*</div>*@

Swaad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Swaad</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />*@
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/75811a9434.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Swaad</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @await Component.InvokeAsync("CategoryMenu")
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FoodItem" asp-action="Index">Food Choices</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Cart</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>*@
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img height="40" src="~/Images/swaad.jpg" /></a>
                @*<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>*@
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active text-white" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i>&nbsp;Home</a></li>
                        <li class="nav-item"><a class="nav-link active text-white" aria-current="page" asp-area="" asp-controller="About" asp-action="Index">About Us</a></li>
                        <li class="nav-item"><a class="nav-link active text-white" aria-current="page" asp-area="" asp-controller="Contact" asp-action="Index">Contact Us</a></li>
                        <li class="nav-item dropdown">
                            @await Component.InvokeAsync("CategoryMenu")
                        </li>
                    </ul>
                    @await Component.InvokeAsync("ShoppingCartIcon")
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="footer-basic bg-dark">
        <footer>
            <div class="social"><a class="bg-white" href="#"><i class="fab fa-instagram"></i></a><a class="bg-white" href="#"><i class="fab fa-linkedin-in"></i></a><a class="bg-white" href="#"><i class="fab fa-twitter"></i></a><a class="bg-white" href="#"><i class="fab fa-facebook-f"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item text-white"><a aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="list-inline-item text-white"><a aria-current="page" asp-area="" asp-controller="About" asp-action="Index">About</a></li>
                <li class="list-inline-item text-white"><a aria-current="page" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a></li>
                <li class="list-inline-item text-white"><a aria-current="page" asp-area="" asp-controller="FoodItem" asp-action="Index">Food Menu</a></li>
            </ul>
            <p class="copyright">Swaad © 2021</p>
        </footer>
    </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>