Swaad/Models/ShoppingCart.cs
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Swaad.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Models
{
    public class ShoppingCart
    {
        private readonly ApplicationDbContext _applicationDbContext;

        public string ShoppingCartId { get; set; }

        public List<ShoppingCartItem> ShoppingCartItems { get; set; }

        public ShoppingCart(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        //GetCart/AddtoCart/RemoveFromcart/GetShoppingitems/clear cart/gettotal

        public static ShoppingCart GetCart(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;
            var context = services.GetService<ApplicationDbContext>();

            string cartId = session.GetString("CartId") ?? Guid.NewGuid().ToString();
            session.SetString("CartId", cartId);
            return new ShoppingCart(context) { ShoppingCartId = cartId };

        }

        public void AddToCart(FoodItem fooditem, int quantity)
        {
            var shoppingCartItem =
                _applicationDbContext.ShoppingCartItems.SingleOrDefault(
                    s => s.FoodItem.FoodId == fooditem.FoodId && s.ShoppingCartId == ShoppingCartId);
            if (shoppingCartItem == null)
            {
                shoppingCartItem = new ShoppingCartItem
                {
                    ShoppingCartId = ShoppingCartId,
                    FoodItem = fooditem,
                    Quantity = 1
                };
                _applicationDbContext.ShoppingCartItems.Add(shoppingCartItem);
            }
            else
            {
                shoppingCartItem.Quantity++;
            }
            _applicationDbContext.SaveChanges();
        }


        public int RemoveFromCart(FoodItem fooditem)
        {

            var shoppingCartItem =
                _applicationDbContext.ShoppingCartItems.SingleOrDefault(
                    s => s.FoodItem.FoodId == fooditem.FoodId && s.ShoppingCartId == ShoppingCartId);
            var localamount = 0;

            if (shoppingCartItem != null)
            {
                if (shoppingCartItem.Quantity > 1)
                {
                    shoppingCartItem.Quantity--;
                    localamount = shoppingCartItem.Quantity;
                }
                else
                {
                    _applicationDbContext.ShoppingCartItems.Remove(shoppingCartItem);
                }
            }
            _applicationDbContext.SaveChanges();

            return localamount;
        }

        public List<ShoppingCartItem> GetShoppingCartItems()
        {
            return ShoppingCartItems ??=
                _applicationDbContext.ShoppingCartItems.Where(c => ShoppingCartId == ShoppingCartId)
                .Include(s => s.FoodItem)
                .ToList();
        }

        public decimal GetShoppingCartTotal()
        {
            var total = _applicationDbContext.ShoppingCartItems.Where(c => ShoppingCartId == ShoppingCartId)
                .Select(c => c.FoodItem.Price * c.Quantity).Sum();
            return total;
        }

        public void ClearCart()
        {
            var rows = from o in _applicationDbContext.ShoppingCartItems select o;
            foreach (var row in rows)
            {
                _applicationDbContext.ShoppingCartItems.Remove(row);
            }
            _applicationDbContext.SaveChanges();
        }
    }
}

Swaad/ViewModels/ShoppingCartViewModel.cs
using Swaad.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.ViewModels
{
    public class ShoppingCartViewModel
    {
        public ShoppingCart ShoppingCart { get; set; }
        public decimal ShoppingCartTotal { get; set; }
    }
}

Swaad/Controllers/FoodItemController.cs
using Microsoft.AspNetCore.Mvc;
using Swaad.Models;
using Swaad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class FoodItemController : Controller
    {
        private readonly IFoodItemRepo _foodItemRepo;
        private readonly ICategoryRepo _categoryRepo;

        //DI

        public FoodItemController(IFoodItemRepo foodItemRepo, ICategoryRepo categoryRepo)
        {
            _foodItemRepo = foodItemRepo;
            _categoryRepo = categoryRepo;
        }

        public IActionResult Index(string FoodSearch)
        {
            ViewData["GetFoodItems"] = FoodSearch;
            var query = _foodItemRepo.AllFoodItems;
            if(!String.IsNullOrEmpty(FoodSearch))
            {
                query = query.Where(x => x.FoodName.Contains(FoodSearch) || x.FoodDescription.Contains(FoodSearch));
            }
            var foodListViewModel = new FoodListViewModel
            {
                FoodItems = query.ToList(),
                CurrentCategory = ""
            };
            return View(foodListViewModel);
        }
        public IActionResult CategoryFilter(string category)
        {
            IEnumerable<FoodItem> fooditems;
            string currentcategory;

            if (string.IsNullOrEmpty(category))
            {
                fooditems = _foodItemRepo.AllFoodItems.OrderBy(f => f.FoodId);
                currentcategory = "all food dishes";
            }
            else
            {
                fooditems = _foodItemRepo.AllFoodItems.Where(f => f.Category.CategoryName == category).OrderBy(f => f.FoodId);
                currentcategory = _categoryRepo.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            return View(new FoodListViewModel { FoodItems = fooditems, CurrentCategory = currentcategory });
        }

        public IActionResult Details(int id)
        {
            var fooditem = _foodItemRepo.GetFoodItemById(id);
            if (fooditem == null)
            {
                return NotFound();
            }
            return View(fooditem);
        }
    }
}

Swaad/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Swaad.Models;
using Swaad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ShoppingCart _shoppingCart;
        public RegisterController(ShoppingCart shoppingCart)
        {
            _shoppingCart = shoppingCart;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Order order)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Checkout");
            }
            return View();
        }

        public ActionResult Checkout()
        {
            ViewBag.CheckoutMsg = "Thanks for you order. Tasty food on the way!";
            
            var checkoutViewModel = new CheckoutViewModel
            {
                shoppingCartItems = _shoppingCart.GetShoppingCartItems(),
                shoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            _shoppingCart.ClearCart();
            return View(checkoutViewModel);
        }
    }
}

Swaad/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using Swaad.Models;
using Swaad.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Swaad.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IFoodItemRepo _foodItemRepo;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IFoodItemRepo foodItemRepo, ShoppingCart shoppingCart)
        {
            _foodItemRepo = foodItemRepo;
            _shoppingCart = shoppingCart;
        }
        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
               
            };

            return View(shoppingCartViewModel);

        }

        public RedirectToActionResult AddToShoppingCart(int fooditemid)
        {
            var selectedFoodItem = _foodItemRepo.AllFoodItems.FirstOrDefault(p => p.FoodId == fooditemid);
            if (selectedFoodItem != null)
            {
                _shoppingCart.AddToCart(selectedFoodItem, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int fooditemid)
        {
            var selectedFoodItem = _foodItemRepo.AllFoodItems.FirstOrDefault(p => p.FoodId == fooditemid);
            if (selectedFoodItem != null)
            {
                _shoppingCart.RemoveFromCart(selectedFoodItem);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult ClearShoppingCart()
        {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

Swaad/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel

<div style="padding-top:80px">
    <h2>Here's Your Shopping Cart!</h2>
    <h3>Great selection of Food Items!</h3>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>FoodItem</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Sub Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-left">
                        @item.FoodItem.FoodName
                    </td>
                    <td class="text-right">
                        ₹ @item.FoodItem.Price
                    </td>
                    <td class="text-center"><a class="btn btn-dark text-white" asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-fooditemid="@item.FoodItem.FoodId">-</a>&nbsp; @item.Quantity &nbsp;<a class="btn btn-dark text-white" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-fooditemid="@item.FoodItem.FoodId">+</a></td>
                    <td class="text-right">₹ @(item.Quantity * item.FoodItem.Price)</td>
                </tr>

            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    ₹ @Model.ShoppingCartTotal
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align:center">
                    <a class="btn btn-dark text-white" asp-controller="FoodItem" asp-action="Index">Go Back</a> &nbsp;
                    <a class="btn btn-dark text-white" asp-controller="ShoppingCart" asp-action="ClearShoppingCart">Clear Cart</a>
                </td>
                @if (Model.ShoppingCartTotal <= 0)
                {
                    <td colspan="2" style="text-align:center">
                        <a class="btn btn-dark text-white" asp-controller="FoodItem" asp-action="Index">Continue Shopping!</a>
                        <a class="btn btn-dark text-white disabled" asp-controller="Register" asp-action="Index">Check out now!</a>
                    </td>
                }
                else
                {
                    <td colspan="2" style="text-align:center">
                        <a class="btn btn-dark text-white" asp-controller="FoodItem" asp-action="Index">Continue Shopping!</a>
                        <a class="btn btn-dark text-white" asp-controller="Register" asp-action="Index">Check out now!</a>
                    </td>
                }
            </tr>
        </tfoot>

    </table>


</div>